# Generated by Django 4.2.2 on 2023-06-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('address', models.CharField(max_length=1024, verbose_name='Address line 1')),
            ],
        ),
    ]
