# Generated by Django 4.2.2 on 2023-07-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test',
            new_name='prescription',
        ),
    ]
