# Generated by Django 4.2.2 on 2023-07-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_test_test_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='prescription',
            new_name='test',
        ),
    ]
